### ISSUE TITLE
Output of any unpaper commands starts with 'Warning: using insecure memory!' line

### ISSUE THREAD

**Issue by Measurity** [unpaper/unpaper#223]
# Fix
https://github.com/paperless-ngx/paperless-ngx/issues/6649#issuecomment-2105332518

# Original post

## Problem
`OCRmyPDF` doesn't work because it expects version information from `unpaper --version` on the first line.
https://github.com/ocrmypdf/OCRmyPDF/blob/f25fb8c63a652bc5e8aadc68e7ef86692c72d045/src/ocrmypdf/subprocess/__init__.py#L182

### Expected output
```
7.0.0
```

### Actual output
```
Warning: using insecure memory!
7.0.0
```

## Cause
Not known; help wanted. Works on Windows via WSL2 docker container, but fails on my TrueNAS system following the installation of https://github.com/Jip-Hop/jailmaker.

## Temporary workaround
1. Rename `unpaper` in `/usr/bin` to something else (like `unpaper-inner`)
2. Create a text file `/usr/bin/unpaper` with this content:
```sh
#!/bin/bash
unpaper-inner "$@" 2>/dev/null
```
3. Run `chmod +x unpaper`
4. Verify that `unpaper --version` in your shell only returns the version number

**Comment by Flameeyes** [comment]
I'm sorry but this is very much not `unpaper`'s doing — the message appear to be common for gpg2 invocations, but I don't think anything here is doing that (it's missing the command name for that), so I suspect it has something to do with whatever the jail tool is using.

There's a number of references to this (https://github.com/search?q=%22Warning%3A+using+insecure+memory%21%22&type=code) but none that appears like a smoking gun.

**Comment by jepler** [comment]
Hi! I saw your post about this on Mastodon. I don't have a solution for this .. however, I have some information.

 * on debian, unpaper indirectly links libgcrypt through libavformat -> libssh-gcrypt
 * functions called at shared library load time in libssh-gcrypt attempt to initialize the libgcrypt secure memory pool, meaning this happens *before* the main() of unpaper
 * setting the maximum locked memory to 0 with ulimit reproduces the message on my debian stable system, no chroots, jails, or docker involved
 * the "insecure memory" message is written to stderr, while the --version string is written to stdout. programs attempting to use the output of `unpaper --version` (and other unpaper invocations) should probably distinguish between stdout and stderr when capturing the output


```sh
$ (ulimit -l 0; unpaper --version)
Warning: using insecure memory!
7.0.0
$ cat /etc/debian_version 
12.5
```

<details>
<summary>gdb stack trace where warning is printed</summary>

```
Breakpoint 1.5, print_warn () at ../../src/secmem.c:282
282	../../src/secmem.c: No such file or directory.
(gdb) where
#0  print_warn () at ../../src/secmem.c:282
#1  _gcry_secmem_set_flags (flags=<optimized out>) at ../../src/secmem.c:528
#2  0x00007fffef4cd106 in _gcry_vcontrol (cmd=<optimized out>, arg_ptr=<optimized out>)
    at ../../src/global.c:591
#3  0x00007fffef4c8789 in gcry_control (cmd=cmd@entry=GCRYCTL_RESUME_SECMEM_WARN)
    at ../../src/visibility.c:80
#4  0x00007ffff5dacb05 in ssh_crypto_init () at ./src/libgcrypt.c:974
#5  0x00007ffff5d7d71b in _ssh_init (constructor=1) at ./src/init.c:82
#6  libssh_constructor () at ./src/init.c:118
#7  0x00007ffff7fcf9ce in call_init
    (env=0x7fffffffde80, argv=0x7fffffffde68, argc=2, l=<optimized out>)
    at ./elf/dl-init.c:74
#8  call_init (l=<optimized out>, argc=2, argv=0x7fffffffde68, env=0x7fffffffde80)
    at ./elf/dl-init.c:26
#9  0x00007ffff7fcfab4 in _dl_init
    (main_map=0x7ffff7ffe2e0, argc=2, argv=0x7fffffffde68, env=0x7fffffffde80)
    at ./elf/dl-init.c:121
#10 0x00007ffff7fe5a70 in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
```

</details>

**Comment by Flameeyes** [comment]
OMG! Thank you so much for that, we'd all be scraching our heads forever! Now I can at least try to get OcrMyPDF to read the right information here :)

And I should probably go back at my idea of providing [an easier programmatic interface](https://flameeyes.blog/2021/01/26/unpaper-re-designing-an-interface/) for unpaper.

(Why is libavformat linking libssh-gcrypt is something that I don't want to start investigating now, but it sounds like it's prone to more than a few problems.)

**Comment by alxhu-dev** [comment]
I had the exact issue some weeks ago (and now again, because my system crashed and havon no backup). If you run Paperless as Docker Compose (in the TrueNAS Jail), you need to add a capability (to the Docker Container **AND** to the TrueNAS Jail).

I think the cap was "IPC_LOCK".
