### ISSUE TITLE
Unpaper 7.0 fails on [updated:] Ubuntu [three platforms], while Unpaper 6.0 works on Ubuntu

### ISSUE THREAD

**Issue by Manamama** [unpaper/unpaper#235]
Platforms: 
1. A "vanilla" Ubuntu. 
2. Termux
3. Prooted Debian under Termux

Versions: Unpaper 7.0, either hand compiled or off apt stores, FFMPEG , either hand compiled or off apt stores, ***some combinations*** fail [tbd which] , while older Unpaper 6.0 works on Ubuntu. 

I am showing specs and detailed results from the Ubuntu, but also some Termux too, FYI:
1.
```
------ 
Operating System: Ubuntu 22.04.5 LTS x86_64 
Kernel: 6.2.0-39-generic 
Shell: /bin/bash 5.1.16 
Python: 3.10.12 
------ 
Display Manager: gdm3 
Display Server: x11 
Windows Manager: Mutter 
Windows Manager Theme: Adwaita 
Desktop Environment: GNOME 42.9 
Desktop Environment theme: Arc-Darker [GTK2/3] 
Icons theme: Adwaita [GTK2/3] 
------ 
Packages: 4925 (dpkg), 28 (flatpak), 50 (snap) 
Terminal: terminator 
System Font: Noto Sans, 14 [GTK2/3] 
Resolution: 1920x1080, 1920x1080 
------ 

```

Plus:
```
ffmpeg -v
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
  configuration: --disable-decoder=amrnb --disable-gnutls --disable-liblensfun --disable-libopencv --disable-podpages --disable-sndio --disable-stripping --enable-avfilter --enable-chromaprint --enable-frei0r --enable-gcrypt --enable-gpl --enable-ladspa --enable-libaom --enable-libaribb24 --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libdc1394 --enable-libdrm --enable-libdvdnav --enable-libdvdread --enable-libfdk-aac --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libiec61883 --enable-libilbc --enable-libjack --enable-libjxl --enable-libklvanc --enable-libkvazaar --enable-libmp3lame --enable-libmysofa --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librabbitmq --enable-librist --enable-librsvg --enable-librubberband --enable-libshine --enable-libsmbclient --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-nonfree --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-openssl --enable-postproc --enable-pthreads --enable-shared --enable-version3 --incdir=/usr/include/x86_64-linux-gnu --libdir=/usr/lib/x86_64-linux-gnu --prefix=/usr --toolchain=hardened --enable-vaapi --enable-libvpl --enable-libxavs2 --enable-libdavs2 --enable-libvmaf --enable-libvvenc --cc=x86_64-linux-gnu-gcc --cxx=x86_64-linux-gnu-g++ --disable-altivec --shlibdir=/usr/lib/x86_64-linux-gnu
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.100 / 61. 19.100
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
```

and your, hand compiled, Unpaper: `unpaper --version
7.0.0`

 

I have tried converting some .jpgs etc. to .ppm and even to .bmp and then to .ppm and to strip all the presumably funny pixel formats (MJPG etc.) - nothing worked. While it works out of the box with older Unpaper: 

```

user@above-hp2-silver:~$ unpaper /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3_unpaper1.ppm -vv
unpaper 7.0.0
License GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-------------------------------------------------------------------------------
Processing sheet #1: /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm -> /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3_unpaper1.ppm
loading file /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm.
Input #0, ppm_pipe, from '/home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: ppm, rgb24, 2000x1383, 25 fps, 25 tbr, 25 tbn
layout: single
pre-mirror: [none]
blackfilter-scan-direction: [horizontal,vertical]
blackfilter-scan-size: [20,20] 
blackfilter-scan-depth: [500,500]
blackfilter-scan-step: [5,5] 
blackfilter-scan-threshold: 242
blackfilter-intensity: 20
noisefilter-intensity: 4
blurfilter-size: [100,100] 
blurfilter-step: [50,50] 
blurfilter-intensity: 0.010000
grayfilter-size: [50,50] 
grayfilter-step: [20,20] 
grayfilter-threshold: 127
mask points: 
mask-scan-direction: [horizontal]
mask-scan-size: [50,50] 
mask-scan-depth: [-1,-1]
mask-scan-step: [5,5] 
mask-scan-threshold: [0.100000,0.100000]
mask-scan-minimum: [100,100]
mask-scan-maximum: [-1,-1]
mask-color: white
deskew-scan-direction: [left,right]deskew-scan-size: 1500
deskew-scan-depth: 0.500000
deskew-scan-range: 0.087266
deskew-scan-step: 0.001745
deskew-scan-deviation: 0.017453
border-scan-direction: [vertical]
border-scan-size: [5,5] 
border-scan-step: [5,5] 
border-scan-threshold: [5,5]
border-align: [none]border-margin: [0,0]
post-mirror: [none]
white-threshold: 229
black-threshold: 170
sheet-background: white
input-files per sheet: 1
output-files per sheet: 1
input-file-sequence:  /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm
output-file-sequence: /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3_unpaper1.jpg

input-file for sheet 1: /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm
output-file for sheet 1: /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3_unpaper1.jpg
sheet size: 2000x1383
...
noise-filter ... deleted 1 clusters.
blur-filter... deleted 0 pixels.

```

{it hangs here for an hour or so, many retries, reproducible}

 vs. working:
```
user@above-hp2-silver:~$ time /usr/bin/unpaper /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3_unpaper1.ppm -vv
unpaper 6.1
License GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-------------------------------------------------------------------------------
Processing sheet #1: /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm -> /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3_unpaper1.ppm
loading file /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm.
[ppm_pipe @ 0x5610158fa040] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, ppm_pipe, from '/home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: ppm, rgb24, 2000x1383, 25 fps, 25 tbr, 25 tbn, 25 tbc
layout: single
blackfilter-scan-direction: [vertical,horizontal]
blackfilter-scan-size: [20,20]
blackfilter-scan-depth: [500,500]
blackfilter-scan-step: [5,5]
blackfilter-scan-threshold: 0.950000
blackfilter-intensity: 20
noisefilter-intensity: 4
blurfilter-size: [100,100]
blurfilter-step: [50,50]
blurfilter-intensity: 0.010000
grayfilter-size: [50,50]
grayfilter-step: [20,20]
grayfilter-threshold: 0.500000
mask points: 
mask-scan-direction: [horizontal]
mask-scan-size: [50,50]
mask-scan-depth: [-1,-1]
mask-scan-step: [5,5]
mask-scan-threshold: [0.100000,0.100000]
mask-scan-minimum: [100,100]
mask-scan-maximum: [-1,-1]
mask-color: 16777215
deskew-scan-direction: [left,right]
deskew-scan-size: 1500
deskew-scan-depth: 0.500000
deskew-scan-range: 5.000000
deskew-scan-step: 0.100000
deskew-scan-deviation: 1.000000
border-scan-direction: [vertical]
border-scan-size: [5,5]
border-scan-step: [5,5]
border-scan-threshold: [5,5]
border-align: []
border-margin: [0,0]
white-threshold: 0.900000
black-threshold: 0.330000
sheet-background: white ffffff
dpi: 300
input-files per sheet: 1
output-files per sheet: 1
input-file-sequence:  /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm
output-file-sequence: /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3_unpaper1.jpg

input-file for sheet 1: /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3.ppm
output-file for sheet 1: /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3_unpaper1.jpg
sheet size: 2000x1383
...
noise-filter ... deleted 0 clusters.
blur-filter... deleted 0 pixels.
auto-masking (1000,691): 0,0,2000,1382 (invalid detection, using full page size)
gray-filter... deleted 815000 pixels.
auto-masking (1000,691): 0,0,2000,1382 (invalid detection, using full page size)
detected rotation left: [0,0,2000,1382]: 0.000000
detected rotation right: [0,0,2000,1382]: 0.000000
rotation average: 0.000000  deviation: 0.000000  rotation-scan-deviation (maximum): 0.017453  [0,0,2000,1382]
rotate (1000,691): 0.000000
auto-masking (1000,691): 0,0,2000,1382 (invalid detection, using full page size)
centering mask [0,0,2000,1382] (1000,691): 0, 0 - NO CENTERING (would shift area outside visible image)
border detected: (0,0,1,1) in [0,0,1999,1382]
aligning mask [0,0,1998,1381] (0,0): 0, 0
writing output.
saving file /home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3_unpaper1.ppm.
Output #0, image2, to '/home/user/Downloads/GSL_GSL_81545_1_8349_1-20_3_unpaper1.ppm':
  Stream #0:0: Unknown: none (ppm)
[image2 @ 0x561015900200] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[image2 @ 0x561015900200] Encoder did not produce proper pts, making some up.

real	0m7.135s
user	0m5.895s
sys	0m0.315s
user@above-hp2-silver:~$ 

```

2. 
On Termux(es) : 
```
~/downloads $ unpaper --version
7.0.0
~/downloads $ uname -a
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Mar 17 16:28:22 CST 2022 aarch64 Android
~/downloads 
```

and with many images, even after stripping all to a .bpm first:
```
unpaper /storage/self/primary/Download/GcIcZAFWkAAAq-V.jpeg.ppm GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.ppm -vv
unpaper 7.0.0
License GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-------------------------------------------------------------------------------
Processing sheet #1: /storage/self/primary/Download/GcIcZAFWkAAAq-V.jpeg.ppm -> GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.ppm
loading file /storage/self/primary/Download/GcIcZAFWkAAAq-V.jpeg.ppm.
Input #0, ppm_pipe, from '/storage/self/primary/Download/GcIcZAFWkAAAq-V.jpeg.ppm':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: ppm, rgb24, 680x508, 25 fps, 25 tbr, 25 tbn
layout: single
blackfilter-scan-direction: [vertical,horizontal]
blackfilter-scan-size: [20,20]
blackfilter-scan-depth: [500,500]
blackfilter-scan-step: [5,5]
blackfilter-scan-threshold: 0.950000
blackfilter-intensity: 20
noisefilter-intensity: 4
blurfilter-size: [100,100]
blurfilter-step: [50,50]
blurfilter-intensity: 0.010000
grayfilter-size: [50,50]
grayfilter-step: [20,20]
grayfilter-threshold: 0.500000
mask points: 
mask-scan-direction: [horizontal]
mask-scan-size: [50,50]
mask-scan-depth: [-1,-1]
mask-scan-step: [5,5]
mask-scan-threshold: [0.100000,0.100000]
mask-scan-minimum: [100,100]
mask-scan-maximum: [-1,-1]
mask-color: 16777215
deskew-scan-direction: [left,right]
deskew-scan-size: 1500
deskew-scan-depth: 0.500000
deskew-scan-range: 5.000000
deskew-scan-step: 0.100000
deskew-scan-deviation: 1.000000
border-scan-direction: [vertical]
border-scan-size: [5,5]
border-scan-step: [5,5]
border-scan-threshold: [5,5]
border-align: []
border-margin: [0,0]
white-threshold: 0.900000
black-threshold: 0.330000
sheet-background: white ffffff
dpi: 300
input-files per sheet: 1
output-files per sheet: 1
input-file-sequence:  /storage/self/primary/Download/GcIcZAFWkAAAq-V.jpeg.ppm
output-file-sequence: GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.ppm

input-file for sheet 1: /storage/self/primary/Download/GcIcZAFWkAAAq-V.jpeg.ppm
output-file for sheet 1: GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.ppm
sheet size: 680x508
...
noise-filter ... deleted 0 clusters.
blur-filter... deleted 0 pixels.
auto-masking (340,254): 0,0,680,507 (invalid detection, using full page size)
gray-filter... deleted 87500 pixels.
auto-masking (340,254): 0,0,680,507 (invalid detection, using full page size)
detected rotation left: [0,0,680,507]: 0.000000
detected rotation right: [0,0,680,507]: 0.000000
rotation average: 0.000000  deviation: 0.000000  rotation-scan-deviation (maximum): 0.017453  [0,0,680,507]
rotate (340,254): 0.000000
auto-masking (340,254): 0,0,680,507 (invalid detection, using full page size)
centering mask [0,0,680,507] (340,254): 0, 0 - NO CENTERING (would shift area outside visible image)
border detected: (0,0,1,1) in [0,0,679,507]
aligning mask [0,0,678,506] (0,0): 0, 0
writing output.
saving file GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.ppm.
Output #0, image2, to 'GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.jpg':
  Stream #0:0: Unknown: none
[image2 @ 0xb400007c536b2280] Encoder did not produce proper pts, making some up.
[image2 @ 0xb400007c536b2280] The specified filename 'GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.ppm' does not contain an image sequence pattern or a pattern is invalid.
[image2 @ 0xb400007c536b2280] Use a pattern such as %03d for an image sequence or use the -update option (with -frames:v 1 if needed) to write a single image.
~/downloads $ 

```

```
~/downloads $ unpaper GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.bmp GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.bmp.jpg -vv
unpaper 7.0.0
License GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-------------------------------------------------------------------------------
Processing sheet #1: GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.bmp -> GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.bmp.jpg
loading file GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.bmp.
Input #0, bmp_pipe, from 'GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.bmp':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: bmp, bgr24, 680x508, 25 fps, 25 tbr, 25 tbn
unpaper: error: unable to open file GcIcZAFWkAAAq-V.jpeg.ppm_unpapered.bmp: unsupported pixel format
Try 'man unpaper' for more information.
~/downloads $ ffmpeg -v
ffmpeg version 6.1.2 Copyright (c) 2000-2024 the FFmpeg developers
  built with Android (12470979, +pgo, +bolt, +lto, +mlgo, based on r522817c) clang version 18.0.3
```

Ver. 2.0.1, the results in Ubuntu reconfirmed in details, see below.

**Comment by Manamama** [comment]
Ok, I am partly wrong, I should have RTFM more (about the input and output image formats), as it sometimes produces valid PPMs... And it works on Termux, after all, ver 7.0. I leave it open, until further experiments, tomorrow...

**Comment by Manamama** [comment]
Ok, 24 hours later, after doing much RTFM, I confirm the Ubuntu part above. 

Ubuntu specs - vide supra. 

A.  Hand compiled: `/home/user/.local/bin/unpaper_7.0_bad  --version
7.0.0` :
```
-vv "/home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm" /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349 Strona 8.jpg.ppm 

unpaper 7.0.0
License GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-------------------------------------------------------------------------------
Processing sheet #1: /home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm -> /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349
loading file /home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm.
Input #0, ppm_pipe, from '/home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: ppm, rgb24, 2000x1383, 25 fps, 25 tbr, 25 tbn
layout: single
pre-mirror: [none]
blackfilter-scan-direction: [horizontal,vertical]
blackfilter-scan-size: [20,20] 
blackfilter-scan-depth: [500,500]
blackfilter-scan-step: [5,5] 
blackfilter-scan-threshold: 242
blackfilter-intensity: 20
noisefilter-intensity: 4
blurfilter-size: [100,100] 
blurfilter-step: [50,50] 
blurfilter-intensity: 0.010000
grayfilter-size: [50,50] 
grayfilter-step: [20,20] 
grayfilter-threshold: 127
mask points: 
mask-scan-direction: [horizontal]
mask-scan-size: [50,50] 
mask-scan-depth: [-1,-1]
mask-scan-step: [5,5] 
mask-scan-threshold: [0.100000,0.100000]
mask-scan-minimum: [100,100]
mask-scan-maximum: [-1,-1]
mask-color: white
deskew-scan-direction: [left,right]deskew-scan-size: 1500
deskew-scan-depth: 0.500000
deskew-scan-range: 0.087266
deskew-scan-step: 0.001745
deskew-scan-deviation: 0.017453
border-scan-direction: [vertical]
border-scan-size: [5,5] 
border-scan-step: [5,5] 
border-scan-threshold: [5,5]
border-align: [none]border-margin: [0,0]
post-mirror: [none]
white-threshold: 229
black-threshold: 170
sheet-background: white
input-files per sheet: 1
output-files per sheet: 1
input-file-sequence:  /home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm
output-file-sequence: /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349

input-file for sheet 1: /home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm
output-file for sheet 1: /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349
sheet size: 2000x1383
...
noise-filter ... deleted 1 clusters.
blur-filter... deleted 0 pixels.
^C
```
- enters into indefinite loop here, seemingly. 

B. Same source file, processed by the apt installed older version : `unpaper --version
6.1` 
```
-vv "/home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm" /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349 Strona 8.jpg.ppm 
unpaper 6.1
License GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

-------------------------------------------------------------------------------
Processing sheet #1: /home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm -> /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349
loading file /home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm.
[ppm_pipe @ 0x557dcfd1d040] Stream #0: not enough frames to estimate rate; consider increasing probesize
Input #0, ppm_pipe, from '/home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm':
  Duration: N/A, bitrate: N/A
  Stream #0:0: Video: ppm, rgb24, 2000x1383, 25 fps, 25 tbr, 25 tbn, 25 tbc
layout: single
blackfilter-scan-direction: [vertical,horizontal]
blackfilter-scan-size: [20,20]
blackfilter-scan-depth: [500,500]
blackfilter-scan-step: [5,5]
blackfilter-scan-threshold: 0.950000
blackfilter-intensity: 20
noisefilter-intensity: 4
blurfilter-size: [100,100]
blurfilter-step: [50,50]
blurfilter-intensity: 0.010000
grayfilter-size: [50,50]
grayfilter-step: [20,20]
grayfilter-threshold: 0.500000
mask points: 
mask-scan-direction: [horizontal]
mask-scan-size: [50,50]
mask-scan-depth: [-1,-1]
mask-scan-step: [5,5]
mask-scan-threshold: [0.100000,0.100000]
mask-scan-minimum: [100,100]
mask-scan-maximum: [-1,-1]
mask-color: 16777215
deskew-scan-direction: [left,right]
deskew-scan-size: 1500
deskew-scan-depth: 0.500000
deskew-scan-range: 5.000000
deskew-scan-step: 0.100000
deskew-scan-deviation: 1.000000
border-scan-direction: [vertical]
border-scan-size: [5,5]
border-scan-step: [5,5]
border-scan-threshold: [5,5]
border-align: []
border-margin: [0,0]
white-threshold: 0.900000
black-threshold: 0.330000
sheet-background: white ffffff
dpi: 300
input-files per sheet: 1
output-files per sheet: 1
input-file-sequence:  /home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm
output-file-sequence: /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349

input-file for sheet 1: /home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm
output-file for sheet 1: /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349
sheet size: 2000x1383
...
noise-filter ... deleted 0 clusters.
blur-filter... deleted 0 pixels.
auto-masking (1000,691): 0,0,2000,1382 (invalid detection, using full page size)
gray-filter... deleted 1652500 pixels.
auto-masking (1000,691): 0,0,2000,1382 (invalid detection, using full page size)
detected rotation left: [0,0,2000,1382]: 0.000000
detected rotation right: [0,0,2000,1382]: 0.000000
rotation average: 0.000000  deviation: 0.000000  rotation-scan-deviation (maximum): 0.017453  [0,0,2000,1382]
rotate (1000,691): 0.000000
auto-masking (1000,691): 0,0,2000,1382 (invalid detection, using full page size)
centering mask [0,0,2000,1382] (1000,691): 0, 0 - NO CENTERING (would shift area outside visible image)
border detected: (0,0,1,1) in [0,0,1999,1382]
aligning mask [0,0,1998,1381] (0,0): 0, 0
writing output.
saving file /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349.
Output #0, image2, to '/home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349':
  Stream #0:0: Unknown: none (ppm)
[image2 @ 0x557dcfd23200] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[image2 @ 0x557dcfd23200] Encoder did not produce proper pts, making some up.
 :~$
 ```
 - works fine.

**Comment by Manamama** [comment]
FYI, a friendly AI advises and opines:

```
input-file-sequence:  /home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm
output-file-sequence: /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349 Strona s8.jpg.ppm

input-file for sheet 1: /home/user/Downloads/GSL_GSL_81545_1_8349_8.jpg.ppm
output-file for sheet 1: /home/user/Downloads/docling_test_4/GSL_GSL_81545_1_8349 Strona s8.jpg.ppm
sheet size: 2000x1383
...
noise-filter ... deleted 1 clusters.
blur-filter... deleted 0 pixels.
  ^C
Program received signal SIGINT, Interrupt.
0x0000555555653805 in inverse_brightness_rect (image=..., input_area=...) at ../imageprocess/blit.c:48
48	  scan_rectangle(area) {
(gdb) bt
#0  0x0000555555653805 in inverse_brightness_rect (image=..., input_area=...)
    at ../imageprocess/blit.c:48
#1  0x0000555555658235 in detect_edge (image=..., origin=origin@entry=..., step=..., 
    scan_size=scan_size@entry=50, scan_depth=<optimized out>, scan_depth@entry=-1, 
    threshold=threshold@entry=0.100000001) at ../imageprocess/masks.c:88
#2  0x00005555556573da in detect_mask (image=..., params=..., origin=..., mask=<optimized out>)
    at ../imageprocess/masks.c:112
#3  detect_masks (image=..., params=..., points=points@entry=0x7fffffffbc10, 
    points_count=points_count@entry=1, masks=masks@entry=0x7fffffffadd0) at ../imageprocess/masks.c:189
#4  0x000055555565268d in main (argc=4, argv=0x7fffffffd7a8) at ../unpaper.c:1697
(gdb) bt
#0  0x0000555555653805 in inverse_brightness_rect (image=..., input_area=...)
    at ../imageprocess/blit.c:48
#1  0x0000555555658235 in detect_edge (image=..., origin=origin@entry=..., step=..., 
    scan_size=scan_size@entry=50, scan_depth=<optimized out>, scan_depth@entry=-1, 
    threshold=threshold@entry=0.100000001) at ../imageprocess/masks.c:88
#2  0x00005555556573da in detect_mask (image=..., params=..., origin=..., mask=<optimized out>)
    at ../imageprocess/masks.c:112
#3  detect_masks (image=..., params=..., points=points@entry=0x7fffffffbc10, 
    points_count=points_count@entry=1, masks=masks@entry=0x7fffffffadd0) at ../imageprocess/masks.c:189
#4  0x000055555565268d in main (argc=4, argv=0x7fffffffd7a8) at ../unpaper.c:1697
(gdb) bt
#0  0x0000555555653805 in inverse_brightness_rect (image=..., input_area=...)
    at ../imageprocess/blit.c:48
#1  0x0000555555658235 in detect_edge (image=..., origin=origin@entry=..., step=..., 
    scan_size=scan_size@entry=50, scan_depth=<optimized out>, scan_depth@entry=-1, 
    threshold=threshold@entry=0.100000001) at ../imageprocess/masks.c:88
#2  0x00005555556573da in detect_mask (image=..., params=..., origin=..., mask=<optimized out>)
    at ../imageprocess/masks.c:112
#3  detect_masks (image=..., params=..., points=points@entry=0x7fffffffbc10, 
    points_count=points_count@entry=1, masks=masks@entry=0x7fffffffadd0) at ../imageprocess/masks.c:189
#4  0x000055555565268d in main (argc=4, argv=0x7fffffffd7a8) at ../unpaper.c:1697
(gdb) 


```


+

```
Valgrind: debuginfo reader: ensure_valid failed:
request for range [164641085, +4) exceeds
valid image size of 107811848 for image:
"/home/user/.local/bin/unpaper_7.0_bad"

```
It looks like the debug trace shows that the program is hanging during the execution of the `inverse_brightness_rect` function in `blit.c`. This function seems to be operating on a specific image area, and the issue could stem from how input areas or memory management is handled within that function.

In your situation, rather than simply tracking the function calls at a high level, consider focusing on how `input_area` is being passed to `inverse_brightness_rect` and whether there are any potential invalid memory accesses or resource exhaustion issues when dealing with large images. 

From the trace:

1. **`inverse_brightness_rect`**: This function is being called with `image` and `input_area` as parameters. It seems to hang here, likely because the function doesn't handle large input areas properly.
2. **`detect_edge` and `detect_mask`**: These functions are handling the image and mask processing and could be where the issue propagates from.

To refine your debugging approach:
- Use a **memory checker** like Valgrind, specifically looking for invalid reads/writes around the `input_area`.
- Focus on **memory allocations** related to image data and areas being passed to each function. It's possible that the program doesn't gracefully handle larger areas or data sizes.
- If possible, check the **bounds** and **validity** of the input data that is passed into each function, especially for large image sizes (like the 2000x1383 sheet size you mentioned).
