### ISSUE TITLE
unpaper with ocrmypdf on Fedora 33

### ISSUE THREAD

**Issue by Mike81269** [unpaper/unpaper#81]
Hello
I try to use unpaper together with ocrmypdf on the new Fedora 33.
I took the last version of unpaper from GitHub and ocrmypdf which is delived together with Fedora 33.
The command is
ocrmypdf -l deu -c -d -i <input.pdf> <output.pdf> 

I would be happy about every hint to solve this problem.
By the way, with the unpaper which is delivered with Fedora 33 is not working - version >=6.1 needed

Error output:

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 189, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 132, in make_intermediate_images
    preprocess_out = preprocess(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 105, in preprocess
    image = preprocess_clean(image, page_context)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 476, in preprocess_clean
    unpaper.clean(input_file, output_file, dpi.x, page_context.options.unpaper_args)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 129, in clean
    run(input_file, output_file, dpi, unpaper_args)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 83, in run
    proc = external_run(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/subprocess.py", line 54, in run
    proc = subprocess_run(args, env=env, **kwargs)
  File "/usr/lib64/python3.9/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib64/python3.9/subprocess.py", line 1117, in communicate
    stdout = self.stdout.read()
  File "/usr/lib64/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 351: invalid start byte
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 362, in run_pipeline
    exec_concurrent(context)
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 269, in exec_concurrent
    exec_progress_pool(
  File "/usr/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 111, in exec_progress_pool
    result = results.next()
  File "/usr/lib64/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 351: invalid start byte

**Comment by Flameeyes** [comment]
I'm afraid I cannot help you with this particular problem because it's not a failure in unpaper (written in C), but rather in ocrmypdf (written in Python), which I have no experience with. Consider reporting this to ocrmypdf maintainers instead.

**Comment by Mike81269** [comment]
HI Flameeyes,
Thanks a lot for your anwser - please check this issue 
https://github.com/jbarlow83/OCRmyPDF/issues/671
An read my last comment - I hope the unpaper and ocrmypdf team can solve together the interface differences
If not would happy to get hints so solve this problem by myself - locally - like I worte.
